apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
  labels:
    app: user-management-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
        - name: user-management-service
          image: ghcr.io/SamirMarin/user-management-service-cicd:88b423f824d14060529f9cc69bbb50660ca82204
          ports:
            - containerPort: 1324
